// TODO Implement this library.// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEcNwDOok_r37pZQ7EpIh6DyZi2erLbBI',
    appId: '1:399764484697:web:102d34ce71ab76e95bf748',
    messagingSenderId: '399764484697',
    projectId: 'volunteerapp-4a508',
    authDomain: 'volunteerapp-4a508.firebaseapp.com',
    storageBucket: 'volunteerapp-4a508.appspot.com',
    measurementId: 'G-VPL4GJMNV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9h5Wlw3-GGTRoGGdR9VyPeJkuKuN5q_s',
    appId: '1:399764484697:android:d963c9af040ddc1a5bf748',
    messagingSenderId: '399764484697',
    projectId: 'volunteerapp-4a508',
    storageBucket: 'volunteerapp-4a508.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6oJSZFn9LHe25oRCbfed1aWLwfB1NBbY',
    appId: '1:399764484697:ios:d3ccb912b5f5c8355bf748',
    messagingSenderId: '399764484697',
    projectId: 'volunteerapp-4a508',
    storageBucket: 'volunteerapp-4a508.appspot.com',
    iosBundleId: 'com.example.ufaTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6oJSZFn9LHe25oRCbfed1aWLwfB1NBbY',
    appId: '1:399764484697:ios:d3ccb912b5f5c8355bf748',
    messagingSenderId: '399764484697',
    projectId: 'volunteerapp-4a508',
    storageBucket: 'volunteerapp-4a508.appspot.com',
    iosBundleId: 'com.example.ufaTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEcNwDOok_r37pZQ7EpIh6DyZi2erLbBI',
    appId: '1:399764484697:web:b17e6261f426e6005bf748',
    messagingSenderId: '399764484697',
    projectId: 'volunteerapp-4a508',
    authDomain: 'volunteerapp-4a508.firebaseapp.com',
    storageBucket: 'volunteerapp-4a508.appspot.com',
    measurementId: 'G-LFHFVKL8RR',
  );
}
